### PR TITLE
Rename package from `ng-pipes` to `ngx-pipes`

### PR DESCRIPTION
**Pull request by danrevah**

### CODE REVIEW

**Comment by rolandjitsu** [comment]
Please make sure that the invalid links are fixed accordingly (look at the Travis build to see which ones need fixing).

**Comment by danrevah** [comment]
Which links need to be fixed? the link I've added is perfectly valid.

**Comment by rolandjitsu** [comment]
Take a look at [188969772#L495](https://travis-ci.org/AngularClass/awesome-angular2/builds/188969772#L495).

**Comment by danrevah** [comment]
@rolandjitsu Done

**Pull request merged**
