### PR TITLE
Remove duplicated the GDE member link

### PR DESCRIPTION
**Pull request by not-for-me**

### CODE REVIEW

**Comment by gdi2290** [comment]
where's the dup?

**Comment by not-for-me** [comment]
@gdi2290 
the second of the list on Experts on Twitter => "@jeffwhelpley" 
and
the 18th of the list on Google Developer Experts => "Jeff Whelpley"

if it's okay, you can just pass!

Thanks in advance

**Comment by gdi2290** [comment]
Jeff is a GDE can you just remove him from experts if you want to ensure experts are non-GDEs. Can you also move kentcdodds from experts to GDE then

**Comment by not-for-me** [comment]
My PR's intent is just remove dup but It's very unclear to classify those members into Experts and GDE.

How about merge two list into the one like below ?

* mhevery (Creator, Lead...)
* .... (GDE)

**Pull request closed without merging**
