### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KyneSilverhide**
Added new Angular 2 Meteor Seed

### CODE REVIEW

**Comment by KyneSilverhide** [comment]
I don' really understand the errors from Travis. 

` Links 
  1. [L310] 301 https://books.ninja-squad.com/angular2  → https://books.ninja-squad.com/angular 
  2. [L324] 302 http://www.webagesolutions.com/courses/WA2533-angular-2-programming  → http://www.webagesolutions.com/courses/WA2533-introduction-to-angular-2-programming 
> Dupes 
  None ✓`

What is wrong with these two links?

**Comment by clacote** [comment]
Hi, I'm from Ninja Squad. We recently made `https://books.ninja-squad.com/angular2` redirect to `https://books.ninja-squad.com/angular`. I don't know your context, but that may be what Travis is trying to tell you.

**Comment by KyneSilverhide** [comment]
Yes, these are perment and temporary redirections, but I don't understand why the travis build is falling these two URLs as "issues"... redirections shouldn't be considered as errors.

**Comment by rolandjitsu** [comment]
@clacote that is correct. The two links both have redirects.

@KyneSilverhide while a `301` is not an actual error, it might be a malicious redirect that was not intended by the author.

Thus Travis failing will enforce a check by a human of the url in question.

**Comment by KyneSilverhide** [comment]
Ok. And how should I manually check these URLs?  Do they need to be added to the whitelist?

**Comment by rolandjitsu** [comment]
Just update the two links you see failing at [#192156747#L499](https://travis-ci.org/AngularClass/awesome-angular2/builds/192156747#L499) with the form on the right. It's not that complicated.

**Comment by KyneSilverhide** [comment]
Ok, I was thinking too hard... links are fixed now.

**Pull request merged**
